/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.binhtran432k.plantumlpreviewer;

import javax.swing.SwingUtilities;

/**
 * Main application
 *
 * @author Tran Duc Binh
 * @since 1.0.0
 *
 */
public class App {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            MainWindow mainWindow = new MainWindow();
            mainWindow.setVisible(true);
        });
    }

}
