/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.binhtran432k.plantumlpreviewer;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Main application
 *
 * @author Tran Duc Binh
 * @since 1.0.0
 *
 */
public class App {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                    | UnsupportedLookAndFeelException ex) {
                ex.printStackTrace();
            }
            MainWindow mainWindow = new MainWindow(args);
            mainWindow.setVisible(true);
        });
    }

}
