/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.binhtran432k.plantumlpreviewer;

import com.github.binhtran432k.plantumlpreviewer.cli.CommandLine;

/**
 * Main application
 *
 * @author Tran Duc Binh
 * @since 1.0.0
 *
 */
public class Runner {

    public static void main(String[] args) {
        new CommandLine(args);
    }

}
